name: Setup
on: [ push, pull_request ]

jobs:
  setup-selenium:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - windowns-latest
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Setup chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SeleniumToolKtTest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew test --tests "xyz.cssxsh.selenium.SeleniumToolKtTest" --scan --info -Dwebdriver.chrome.bin=/Users/runner/hostedtoolcache/chromium/latest/x64/Chromium.app/Contents/MacOS/Chromium