name: Setup
on: [ push, pull_request ]

jobs:
  setup-selenium:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-11
          - ubuntu-latest
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SeleniumToolKtTest
        run: ./gradlew test --tests "xyz.cssxsh.selenium.SeleniumToolKtTest" --scan